version: '3.3'

services:

# MPD
  mpd:
    privileged: true
    image: vimagick/mpd
    ports:
      - "6600:6600"
      - "8000:8000"
    volumes:
      - ./mpd/mpd.conf:/etc/mpd.conf
      - ./music:/var/lib/mpd/music
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# YMPD - MPD-GUI
  ympd:
    image: knapoc/docker-ympd
    ports:
      - "80:8080"
    depends_on:
      - mpd
    restart: unless-stopped
    links:
      - mpd:mpdhost
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# AShuffle - keeps the queue at a given length
  ashuffle:
    image: hradio/ashuffle
    environment:
      - QUEUE_BUFFER=10
    depends_on:
      - mpd
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# edihttp-splitter
  edihttp:
    image: hradio/edihttp
    ports:
      - "8187:8187"
    depends_on:
      - mpd
    volumes:
      - ./hradio-edihttp/edihttp.conf:/root/edihttp.conf
#    environment:
#    - EDIHTTP_CONFIGPATH=
#    - EDIHTTP_MAX_TIMESHIFT_GLOBAL=
#    - EDIHTTP_SBT_SUBCHANS=
#    - EDIHTTP_VERBOSE=
#    - EDIHTTP_UDP_PORT=
#    - EDIHTTP_HTTP_PORT=
#    - EDIHTTP_PROXY_PORT=
#    - EDIHTTP_HOSTS=
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# PAD-Generator
  mpd-pad:
    image: hradio/mpd-pad
    volumes:
      - ./odr-padenc/service1/:/dab/service1/
      - ./music:/music
    environment:
    - HRADIO_DLPOUTPUTFILE=/dab/service1/dls/dls_1.txt
    - HRADIO_MEDIABASEPATH=/music/
    - HRADIO_SLSOUTPUTPATH=/dab/service1/sls/
    depends_on:
      - mpd
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# ODR-DABMux
  odr-dabmux:
    privileged: true
    image: hradio/odr-dabmux
    volumes:
      - ./odr-dabmux/mux.conf:/etc/dab/mux.conf
    depends_on:
      - mpd
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# ODR-PADEnc
  odr-padenc-service1:
    image: hradio/odr-padenc
    volumes:
      - ./odr-padenc/service1/:/dab/service1/
      - pad_volume:/output/
    environment:
    - PADENC_OUTPUT=/output/service1.pad #FIFO to write PAD data into.
    - PADENC_INPUT_DLS=/dab/service1/dls/dls_1.txt #FIFO or file to read DLS text from.
    - PADENC_INPUT_SLS=/dab/service1/sls #Directory to read images from.
    - PADENC_DELAY=1 #Wait DELAY seconds between each slide
    - PADENC_FRAME=40 #Frame length for uniform mode
    - PADENC_PADSIZE=116 #Set PAD size in bytes.
    - PADENC_OTHERS= -s 3 #E.g. -R for Do not process slides integrity checks and resizing
    depends_on:
      - mpd
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# ODR-AudioEnc
  odr-audioenc-service1:
    build: ./hradio-odr-audioenc/
    volumes:
      - pad_volume:/input/
    environment:
    - AUDIOENC_INPUT=http://mpd:8000/ # input url
    - AUDIOENC_OUTPUT=tcp://odr-dabmux:9001 #output - see mux.conf
    - AUDIOENC_BITRATE=128 #Output bitrate in kbps. Must be a multiple of 8
    - AUDIOENC_PADSIZE=116 #Set PAD size in bytes.
    - AUDIOENC_PADFILE=/input/service1.pad #Set PAD data input fifo name
    - AUDIOENC_OTHERS= #E.g. --aaclc
    depends_on:
      - mpd
      - odr-dabmux
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"

# ODR-DABMod
  odr-dabmod:
    privileged: true
    image: hradio/odr-dabmod
    volumes:
      - ./odr-dabmod/mod.conf:/etc/dab/mod.conf
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bus/usb/:/dev/bus/usb/
    depends_on:
      - mpd
      - odr-dabmux
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "2"


volumes:
    pad_volume: {}